---
abstract: 'Store a filesystem in a relational database'
author:
  - 'Lincoln Stein <lincoln.stein@oicr.on.ca>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: sqlfs-perl
provides:
  DBI::Filesystem:
    file: lib/DBI/Filesystem.pm
    version: 1.01
  DBI::Filesystem::DBD::Pg:
    file: lib/DBI/Filesystem/DBD/Pg.pm
    version: 0
  DBI::Filesystem::DBD::SQLite:
    file: lib/DBI/Filesystem/DBD/SQLite.pm
    version: 0
  DBI::Filesystem::DBD::mysql:
    file: lib/DBI/Filesystem/DBD/mysql.pm
    version: 0
requires:
  DBI: 0
  Fuse: 0.15
  threads: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
